abstract: Administer IIS webserver on Windows
author: Martin Thurn (mthurn@cpan.org)
build_requires:
  IO::Capture::Stderr: 0
  Test::Simple: 0.44
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Win32-IIS-Admin
no_index:
  directory:
    - inc
    - t
recommends:
  Win32API::File: 0
requires:
  Data::Dumper: 0
  File::Spec: 0
version: 1.008
