--- 
abstract: Administer IIS webserver on Windows
author: 
  - Martin Thurn (mthurn@cpan.org)
build_requires: 
  IO::Capture::Stderr: 0
  Test::More: 0
  Test::Simple: 0.44
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Win32-IIS-Admin
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Win32API::File: 0
requires: 
  Data::Dumper: 0
  File::Spec: 0
  IO::String: 0
version: 1.023
